# Use postgres/example user/password credentials

services:

  db:
    image: postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: senha
volumes:
  postgres-data:
  
